// Regenerates lib/src/data/bundled_matrix.g.dart from data/matrix.json after
// validating it. Run from the package root: dart run tool/embed_matrix.dart
import 'dart:io';

import 'package:droid_doctor/src/data/compat_matrix.dart';

const _output = 'lib/src/data/bundled_matrix.g.dart';

void main() {
  final json = File('data/matrix.json').readAsStringSync();
  if (json.contains("'''")) {
    stderr.writeln("data/matrix.json must not contain '''");
    exit(1);
  }
  CompatMatrix.parse(json); // Throws with a precise message if invalid.
  File(_output).writeAsStringSync(embedMatrix(json));
  stdout.writeln('Wrote $_output');
}

String embedMatrix(String json) => '''
// GENERATED by tool/embed_matrix.dart from data/matrix.json. Do not edit.

/// The compatibility matrix bundled with this release, so checks work offline.
const bundledMatrixJson = r\'\'\'
$json\'\'\';
''';
