// GENERATED by tool/embed_matrix.dart from data/matrix.json. Do not edit.

/// The compatibility matrix bundled with this release, so checks work offline.
const bundledMatrixJson = r'''
{
  "schemaVersion": 1,
  "updated": "2026-10-06",
  "sources": {
    "gradle-java": "https://docs.gradle.org/current/userguide/compatibility.html#java",
    "agp-gradle": "https://developer.android.com/build/releases/gradle-plugin#updating-gradle",
    "agp-java": "https://developer.android.com/build/jdks",
    "kgp": "https://kotlinlang.org/docs/gradle-configure-project.html#apply-the-plugin",
    "flutter": "https://github.com/flutter/flutter/blob/0e98c1f72caa0777cdc1f99a673418009f1a4fde/packages/flutter_tools/lib/src/android/gradle_utils.dart"
  },
  "unknownFrom": {
    "java": "26",
    "gradle": "9.4",
    "agp": "9.3",
    "kgp": "2.5"
  },
  "releases": {
    "gradle": ["7.0", "7.0.2", "7.2", "7.3", "7.3.3", "7.4", "7.5", "7.6", "7.6.3", "8.0", "8.1", "8.1.1", "8.2", "8.4", "8.5", "8.6", "8.7", "8.9", "8.10", "8.10.2", "8.11.1", "8.13", "8.14", "8.14.3", "9.1.0", "9.3.1"],
    "agp": ["7.0.4", "7.1.3", "7.2.1", "7.3.1", "7.4.2", "8.0.0", "8.1.0", "8.2.2", "8.3.1", "8.5.0", "8.6.0", "8.7.0", "8.7.2", "8.8.0", "8.9.0", "8.10.0", "8.11.1", "9.0.1", "9.1.0"],
    "kgp": ["1.7.10", "1.7.20", "1.8.0", "1.8.20", "1.8.22", "1.9.0", "1.9.20", "1.9.25", "2.0.0", "2.0.20", "2.0.21", "2.1.0", "2.1.20", "2.1.21", "2.2.0", "2.2.20", "2.3.0", "2.3.10", "2.3.20", "2.4.0"]
  },
  "rules": [
    {"when": "java", "in": {"min": "25", "max": "26"}, "require": "gradle", "range": {"min": "9.1.0"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "24", "max": "25"}, "require": "gradle", "range": {"min": "8.14"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "23", "max": "24"}, "require": "gradle", "range": {"min": "8.10"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "22", "max": "23"}, "require": "gradle", "range": {"min": "8.7"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "21", "max": "22"}, "require": "gradle", "range": {"min": "8.4"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "20", "max": "21"}, "require": "gradle", "range": {"min": "8.1"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "19", "max": "20"}, "require": "gradle", "range": {"min": "7.6"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "18", "max": "19"}, "require": "gradle", "range": {"min": "7.5"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "17", "max": "18"}, "require": "gradle", "range": {"min": "7.3"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "16", "max": "17"}, "require": "gradle", "range": {"min": "7.0", "max": "9"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "15", "max": "16"}, "require": "gradle", "range": {"min": "6.7", "max": "9"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "14", "max": "15"}, "require": "gradle", "range": {"min": "6.3", "max": "9"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "13", "max": "14"}, "require": "gradle", "range": {"min": "6.0", "max": "9"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "12", "max": "13"}, "require": "gradle", "range": {"min": "5.4", "max": "9"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "11", "max": "12"}, "require": "gradle", "range": {"min": "5.0", "max": "9"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "10", "max": "11"}, "require": "gradle", "range": {"min": "4.7", "max": "9"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "9", "max": "10"}, "require": "gradle", "range": {"min": "4.3", "max": "9"}, "source": "gradle-java"},
    {"when": "java", "in": {"min": "8", "max": "9"}, "require": "gradle", "range": {"min": "2.0", "max": "9"}, "source": "gradle-java"},

    {"when": "agp", "in": {"min": "9.1", "max": "9.2"}, "require": "gradle", "range": {"min": "9.3.1"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "9.0", "max": "9.1"}, "require": "gradle", "range": {"min": "9.1.0"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "8.11", "max": "8.14"}, "require": "gradle", "range": {"min": "8.13"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "8.9", "max": "8.11"}, "require": "gradle", "range": {"min": "8.11.1"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "8.8", "max": "8.9"}, "require": "gradle", "range": {"min": "8.10.2"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "8.7", "max": "8.8"}, "require": "gradle", "range": {"min": "8.9"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "8.5", "max": "8.7"}, "require": "gradle", "range": {"min": "8.7"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "8.4", "max": "8.5"}, "require": "gradle", "range": {"min": "8.6"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "8.3", "max": "8.4"}, "require": "gradle", "range": {"min": "8.4"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "8.2", "max": "8.3"}, "require": "gradle", "range": {"min": "8.2"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "8.0", "max": "8.2"}, "require": "gradle", "range": {"min": "8.0"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "7.4", "max": "8.0"}, "require": "gradle", "range": {"min": "7.5"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "7.3", "max": "7.4"}, "require": "gradle", "range": {"min": "7.4"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "7.2", "max": "7.3"}, "require": "gradle", "range": {"min": "7.3.3"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "7.1", "max": "7.2"}, "require": "gradle", "range": {"min": "7.2"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "7.0", "max": "7.1"}, "require": "gradle", "range": {"min": "7.0"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "4.2", "max": "7.0"}, "require": "gradle", "range": {"min": "6.7.1"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "4.1", "max": "4.2"}, "require": "gradle", "range": {"min": "6.5"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "4.0", "max": "4.1"}, "require": "gradle", "range": {"min": "6.1.1"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "3.6", "max": "3.7"}, "require": "gradle", "range": {"min": "5.6.4"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "3.5", "max": "3.6"}, "require": "gradle", "range": {"min": "5.4.1"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "3.4", "max": "3.5"}, "require": "gradle", "range": {"min": "5.1.1"}, "source": "agp-gradle"},
    {"when": "agp", "in": {"min": "3.3", "max": "3.4"}, "require": "gradle", "range": {"min": "4.10.1"}, "source": "agp-gradle"},

    {"when": "agp", "in": {"min": "8.0"}, "require": "java", "range": {"min": "17"}, "source": "agp-java"},
    {"when": "agp", "in": {"min": "7.0", "max": "8.0"}, "require": "java", "range": {"min": "11"}, "source": "agp-java"},
    {"when": "agp", "in": {"min": "4.2", "max": "7.0"}, "require": "java", "range": {"min": "8"}, "source": "agp-java"},

    {"when": "kgp", "in": {"min": "2.4.0", "max": "2.5"}, "require": "gradle", "range": {"min": "8.5", "max": "9.6"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.3.0", "max": "2.4"}, "require": "gradle", "range": {"min": "7.6.3", "max": "9.6"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.2.0", "max": "2.3"}, "require": "gradle", "range": {"min": "7.6.3", "max": "8.15"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.1.20", "max": "2.2"}, "require": "gradle", "range": {"min": "7.6.3", "max": "8.13"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.1.0", "max": "2.1.20"}, "require": "gradle", "range": {"min": "7.6.3", "max": "8.11"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.0.20", "max": "2.1"}, "require": "gradle", "range": {"min": "6.8.3", "max": "8.9"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.0.0", "max": "2.0.20"}, "require": "gradle", "range": {"min": "6.8.3", "max": "8.6"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.9.20", "max": "2.0"}, "require": "gradle", "range": {"min": "6.8.3", "max": "8.1.1", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.8.20", "max": "1.9.20"}, "require": "gradle", "range": {"min": "6.8.3", "max": "7.6.0", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.8.0", "max": "1.8.20"}, "require": "gradle", "range": {"min": "6.8.3", "max": "7.3.3", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.7.20", "max": "1.8.0"}, "require": "gradle", "range": {"min": "6.7.1", "max": "7.1.1", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.7.0", "max": "1.7.20"}, "require": "gradle", "range": {"min": "6.7.1", "max": "7.0.2", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.6.20", "max": "1.7.0"}, "require": "gradle", "range": {"min": "6.1.1", "max": "7.0.2", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},

    {"when": "kgp", "in": {"min": "2.4.0", "max": "2.5"}, "require": "agp", "range": {"min": "8.2.2", "max": "9.3"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.3.10", "max": "2.4"}, "require": "agp", "range": {"min": "8.2.2", "max": "9.3"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.3.0", "max": "2.3.10"}, "require": "agp", "range": {"min": "8.2.2", "max": "8.14"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.2.20", "max": "2.3.0"}, "require": "agp", "range": {"min": "7.3.1", "max": "8.12"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.2.0", "max": "2.2.20"}, "require": "agp", "range": {"min": "7.3.1", "max": "8.11"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.1.0", "max": "2.2.0"}, "require": "agp", "range": {"min": "7.3.1", "max": "8.7.2", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.0.20", "max": "2.1.0"}, "require": "agp", "range": {"min": "7.1.3", "max": "8.6"}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "2.0.0", "max": "2.0.20"}, "require": "agp", "range": {"min": "7.1.3", "max": "8.3.1", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.9.20", "max": "2.0.0"}, "require": "agp", "range": {"min": "4.2.2", "max": "8.1.0", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.9.0", "max": "1.9.20"}, "require": "agp", "range": {"min": "4.2.2", "max": "7.4.0", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.8.20", "max": "1.9.0"}, "require": "agp", "range": {"min": "4.1.3", "max": "7.4.0", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.8.0", "max": "1.8.20"}, "require": "agp", "range": {"min": "4.1.3", "max": "7.2.1", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.7.20", "max": "1.8.0"}, "require": "agp", "range": {"min": "3.6.4", "max": "7.0.4", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"},
    {"when": "kgp", "in": {"min": "1.6.20", "max": "1.7.20"}, "require": "agp", "range": {"min": "3.4.3", "max": "7.0.2", "maxInclusive": true}, "aboveMax": "warning", "source": "kgp"}
  ],
  "flutter": [
    {
      "version": "3.47",
      "error": {"java": "17", "gradle": "8.14", "agp": "8.11.1", "kgp": "2.2.20", "minSdk": 23},
      "warn": {"java": "17", "gradle": "9.1.0", "agp": "9.0.1", "kgp": "2.3.20", "minSdk": 24},
      "template": {"gradle": "9.3.1", "agp": "9.1.0", "kgp": "2.4.0", "compileSdk": 36, "minSdk": 24}
    }
  ]
}
''';
